### ISSUE TITLE
pre-commit hook

### ISSUE THREAD

**Issue by Lucas-C** [pyupio/safety#10]
Hi,

This is just to let you know that I developped a [pre-commit hook](http://pre-commit.com) based on your lib:
https://github.com/Lucas-C/pre-commit-hooks-safety

It is not yet fully functional : a small limitation in `pre-commit` is a blocker, but I intend to fix it in this issue:
https://github.com/pre-commit/pre-commit/issues/426

**Comment by Lucas-C** [comment]
Alternatively, is there a way to analyze a single requirements file instead of the whole current environment ?

**Comment by jayfk** [comment]
Thanks @Lucas-C, that's awesome. You can read a single file from stdin using the `--stdin` flag, although I'm not quite sure it this will work in this context.

Also, there's a [small bug](https://github.com/pyupio/safety/issues/6) right now using stdin. I'm going to fix that next.

**Comment by jayfk** [comment]
FYI: I've added the pre-commit hook to the [README](https://github.com/pyupio/safety-db/blob/master/README.md). 

Also, since this is super useful: Is there some way `safety` could make that easier in general? Are you able to run arbitrary Python code with the commit hook? Maybe we could just add a function to `safety` to support this better.

**Comment by Lucas-C** [comment]
The `--from-file` suggestion from https://github.com/pyupio/safety/issues/6 sounds great !
It would be even cleaner than a workaround in pre-commit/pre-commit#426

**Comment by Lucas-C** [comment]
To have a perfectly seamless integration with `pre-commit`, a CLI option like this would be the best:
```
parser.add_argument('filenames', nargs='*', help='filenames to check')
```

This way, the `python-safety-dependencies-check` hook could be configured to only run when `requirements` files are modified, and thoses files would be passed to the `safety` command.

**Comment by jayfk** [comment]
Could you check #6 if that solves the problem?

**Comment by Lucas-C** [comment]
Looks perfect ! I just added a couple of comments to the commit: https://github.com/pyupio/safety/commit/2884da8c

**Comment by Lucas-C** [comment]
Closing this: the hook now works perfectly, even with multiple requirements in a repo.
