### ISSUE TITLE
Issue with GitHub integration

### ISSUE THREAD

**Issue by chgad** [pyupio/safety#100]
* safety version: GitHub integration
* Python version: 2.7.x
* Operating System:

### Description

We have an status integrated for varryfying each PR going into the master branch.

I now encounter that this status is Pending for over 12 hours.

Is there currently a server issue or am I doing something wrong with the integration?

**Comment by jayfk** [comment]
There are currently no (known) global server issues. The most reasonable explanation is that one of the worker processes wasn't able to correctly set the commit status.

Is this on a private repo? If so, could you sent me the repo name and the commit sha via mail to support@pyup.io?

If not, please send me a link to the PR on GitHub and I'll have a look at it.

**Comment by chgad** [comment]
Well,
I "reencounter" this Problem, but i found smth which seeems like a bug to me.
So the pyup/saftey Integration works fine when using feature branches and Pr them into our develop branch. Now when Pring into master it stays on "waiting for satus report".

**But** if i do a normal commit on the develop branch (which i'd like to prevent in the future) and push this commit, the status is reported immediately.
This really looks like a Bug. @jayfk  reopen this Issue ?

**Comment by jayfk** [comment]
Could you check if there are any webhooks not being sent to pyup.io and/or are throwing errors?

If you go into your repos settings, you should see a webhook pointing to pyup.io. A click on `edit` should show you all calls to the api (you need to scroll down a bit).

**Comment by chgad** [comment]
Strangely,

it seems that all Request were succesfull even if i encountered "perma-pending" statuses.

**Comment by chgad** [comment]
Update:

I first thought it might be an issue of "not calling the hook when creating the PR". But i doubled checked it and yes, I'm calling the hook when a PR is opened etc. . And the Response looks fine to me.

But still, pending.

**Comment by ilyavw** [comment]
Running into something similar, if I rebase my branch and force push it, the commit status will hang in pending, but if I make a new commit and push it everything will run as expected.

**Comment by jayfk** [comment]
> Running into something similar, if I rebase my branch and force push it, the commit status will hang in pending, but if I make a new commit and push it everything will run as expected.

Thanks, that helps a lot. I'm struggling to reproduce this on a minimal test repo. Maybe that will help.

I'll keep you posted.

**Comment by jayfk** [comment]
I've just deployed some changes that hopefully fix this issue.

@chgad @ilyavw could you try reproducing the bug on one of your repos? If it still doesn't work, could you give me the exact steps that you were doing?

```
- git branch foo
- git checkout foo
- touch bar.txt
- git commit -a -m 'baz'
- git push origin foo
- [created PR on GitHub through UI]
- ...
- ...
```

**Comment by chgad** [comment]
I'm currently on vacation. I'll try it as soon as I'm back.

**Comment by ilyavw** [comment]
Unfortunately I was able to still reproduce this. Here are my steps:

```
- git checkout -b test-branch
- vim README.md
- git commit -am "test commit 1"
- vim README.md
- git commit -am "test commit 2"
- vim tox.ini
- git commit -am "test commit 3"
- git push
-- At this point the 3 commits are pushed together and safety ci still works, as the job only runs on the last commit

- vim tox.ini
- git commit -am "test commit 3" --amend
- git push --force
-- Still working

- vim tox.ini
- git commit -am "test commit 4"
- git push
-- Added a second "buildable" commit, still working

- vim tox.ini
- git commit -am "test commit 4" --amend
- git push -f
-- At this point safety ci hangs
```
<img width="417" alt="image" src="https://user-images.githubusercontent.com/34514071/36263199-acd91400-1237-11e8-833c-9a3fa69dfebe.png">
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/34514071/36263213-b5d09b8c-1237-11e8-9d59-6cb962f198f8.png">

**Comment by ilyavw** [comment]
Ah, that was it! I messed up the syntax in the tox file and that's what caused the failure. I can confirm now that this issue appears to be resolved. Thank you!

**Comment by rafaelpivato** [comment]
Closing this as it is apparently fixed given the conversation above. Let me know otherwise, please.
