### ISSUE TITLE
Input filenames instead of --stdin

### ISSUE THREAD

**Issue by asottile** [pyupio/safety#11]
`--stdin` is rather inflexible in that it requires a shell or other means of piping data to the executable.

I'm proposing a `--input-file` which works similarly but obsoletes `--stdin`

`cat requirements.txt | safety --stdin` becomes `safety -- requirements.txt`

`echo 'x==1' | safety --stdin` becomes `echo 'x==1' | safety -- /dev/stdin`

etc.

**Comment by jayfk** [comment]
I think there's a place for both, reading from stdin and from a file. I've added an `-r` option that behaves just like pips `pip install -r requirements.txt` and resolves referenced files.

**Comment by asottile** [comment]
Why have two ways to do it?

`--stdin` does the same as `-r /dev/stdin` right?

**Comment by jayfk** [comment]
No, `-r` also tries to read referenced files.

If you have a requirements.txt like this:

```
django=1.2.3
-r main.txt
```

and you read that from stdin, you have no way to tell where `main.txt` is located.

If you read in the file and have a file path, you can resolve `main.txt` and read that too.

**Comment by asottile** [comment]
I don't see how that's different between `--stdin` and `-r /dev/stdin`?  They'll both equally be unable to locate files that contain `-r`.

**Comment by jayfk** [comment]
Yup. The difference is that `--stdin` don't even tries to read them. Really, it's just a minor thing.

**Comment by asottile** [comment]
At least with unix tools, they strive to make things not have two-ways-to-do-things, the primary reason I opened this ticket :)
