### ISSUE TITLE
Implicit dependency on pip

### ISSUE THREAD

**Issue by jayvdb** [pyupio/safety#114]
* safety version: master, 1.7.0  , 0.5.1
* Python version: any
* Operating System: any

### Description

Somewhat related to https://github.com/pyupio/safety/issues/90 , safety has a dependency on pip which is not declared in the requirements.

Instead `requirements_dev.txt` has `pip==9.0.1`

Currently the listed dependencies are
- Click>=6.0
- requests
- packaging
- dparse>=0.2.1

dparse `master` depends on pipenv, which depends on pip, but dparse latest release 0.2.1 does not include pip as a dependency, so on a brand new install of Python, running setup.py results in a missing dependency, unless `ensurepip` is used.  Not a very likely scenario, but still not desirable.

But more importantly, it is nice to declare dependencies in the package metadata.  Especially when that dependency has forever said that it isnt a library to be imported ;-)

**Comment by jayfk** [comment]
> But more importantly, it is nice to declare dependencies in the package metadata. Especially when that dependency has forever said that it isnt a library to be imported ;-)

Totally agree here, also on the relying on pip part. Any recommendations going forward?

Try/catch importing `get_installed_distributions` should work, but ideally I'd like to drop the dependency on pip all together. Help on that is greatly appreciated.

**Comment by jayvdb** [comment]
Well `pip` wants to be called as a cmdline app, so why not run `pip list --some --args` to get the desired list and then parse it.  If they dont have a cmd line that does what safety needs, we could ask them to create one.

Then a consideration is which versions of pip are needed to run the required command, and using that as the minimum requirement in `safety` dependencies.

**Comment by jayfk** [comment]
Yep, that‘s a pretty good idea.

**Comment by jayfk** [comment]
`pip` is now a declared dependency: https://github.com/pyupio/safety/blob/master/setup.py#L21
The transitive `pipenv` dependency has been removed with dparse `0.4.1`.

Calling `pip` through the commandline is going to be a major foo on windows. I'm going to try/catch the API breakage while continuing using the internal API. 

Not ideal, but this is packaging. No one expected this to be easy.
