### ISSUE TITLE
Output vulnerable packages to stderr

### ISSUE THREAD

**Issue by adiroiban** [pyupio/safety#131]
### Description

This is a feature request.

It would be nice that when running in CI mode, safety can output the errors to stderr.
In this way, it would be easier to highlight them in the whole CI output.

I see that the current design for formatter/reported does not make it easy to make the distinction between the normal banner and extra formatting and the actual error report.

So at this point, I don't know if it make sense to redesign, but I just wanted to report this so that in the case there is a redesign for this part of the code you can consider making this type of filtering easier :)

Thanks for the nice tool!

**Comment by rafaelpivato** [comment]
Well done looking into Safety reporters. At this moment we have merged some code changes that will print warning messages and errors to stderr. Reports themselves are not actual errors, so they get not written to stderr. What we could have is some special kind of reporter writing vulnerable packages to stdout.

Maybe some **ci-reporter** that would dump verified packages to stdout and vulnerables to stderr.

**Comment by dylanpulver** [comment]
Hi @adiroiban,

Thank you for your feature request and for your patience as we reviewed it.

We understand the importance of having errors output to stderr, especially for easier highlighting in CI environments. We believe that recent changes to Safety have addressed this need by printing warning messages and errors to stderr. Reports themselves, however, are not treated as errors and thus are not written to stderr by default.

To confirm if the current implementation meets your requirements, could you please test the latest version of Safety in your CI environment? If you find that the issue persists or have specific needs that are not met, please let us know with details, and we will look into it further.

Thank you for your continued support and for helping us improve Safety!

Best Regards,
The Safety Team
