### ISSUE TITLE
Add GitLab integration

### ISSUE THREAD

**Issue by girardinsamuel** [pyupio/safety#145]
* safety version:
* Python version:
* Operating System:

### Description

I have not found any GitLab integration yet. Do you plan to add GitLab integration ? 
If not do you think it is something doable ? I can try to open a PR to integrate this.

Thank you in advance
PS: great work by the way for this package 👍

**Comment by lhoekenga** [comment]
+1

**Comment by rafaelpivato** [comment]
Fixed with #220
