### ISSUE TITLE
How can I obtain the CVE of the vulnerabilities?

### ISSUE THREAD

**Issue by nilp0inter** [pyupio/safety#147]
Hi,

Is there a way of print a report including CVE id of the vulnerabilities?

**Comment by chowmean** [comment]
You can get it from here.. https://github.com/pyupio/safety-db/blob/master/data/insecure_full.json
But this also doesn't have all the CVE. Some of them are NULL. 
If its not just python you can get the common vulnerabilities ON CVE website https://cve.mitre.org/cve/search_cve_list.html

**Comment by maaaaz** [comment]
Please include the CVE in the report:

First, this line should be adapted
https://github.com/pyupio/safety/blob/955de595563482f103d5b7871598ce582baeafbd/safety/safety.py#L14

And then this one https://github.com/pyupio/safety/blob/955de595563482f103d5b7871598ce582baeafbd/safety/safety.py#L145

**Comment by rback123** [comment]
A little data enrichment in the report could go a long ways.

**Comment by rafaelpivato** [comment]
Just in case, you can use the **--full-report** option. Let me know if that is not enough.

**Comment by sparrowt** [comment]
I realise this is an old issue so happy to open a new one, but it would really help if the `"cve"` field from `insecure_full.json` was returned by `safety.check`. I don't see any equivalent to the `--full-report` option you mentioned, for use when calling `check()` programmatically.
