### ISSUE TITLE
Wrong error code on Windows.

### ISSUE THREAD

**Issue by dumol** [pyupio/safety#153]
* safety version: 1.8.4
* Python version: 2.7.15
* Operating System: Windows XP

### Description

We try to integrate `safety` checks in https://github.com/chevah/python-package/. It works as advertised for a wide variety of platforms, but on Windows the error code is always zero, even if vulnerabilities are found.

### What I Did

Eg., if I build our Python package from branch `4974-safety-pip-module` with an older PyCryptodome, run `safety` and check error code:
```
checked 27 packages, using default DB

---

-> pycryptodome, installed 3.6.5, affected <3.6.6, id 36384

pycryptodome before 3.6.6 has a vulnerability on AESNI ECB with payloads smaller than 16 bytes.

--

Error code from safety is: 0
```
On all the other platforms (Linux, OS X, various Unices and BSDs) the error code is not zero and we can catch it and act on it.

Anyway, thanks for `safety`, a great project that eases our (also open-source) effort to package Python for many platforms!

**Comment by rafaelpivato** [comment]
Thanks for reporting this, and sorry for taking so long to give you a feedback. We just tested this on a Windows 7 machine and the exit code looks good. I will be closing this but feel free to let us know if you still have issues.

**Comment by dumol** [comment]
Thanks for checking it! I can't see it being on issue on our Windows slaves either.

However, this was reported on XP, and I think at that time we only built our Windows Python package on XP. In the meantime, we switched to building on Windows 2016 and 2019.
