### ISSUE TITLE
Dockerise safety

### ISSUE THREAD

**Issue by o6uoq** [pyupio/safety#155]
### Description

Dockerise the safety command/tool to make it easier to be used in local development and within CI/CD pipelines.

### What I Did

Here's a copy of my Dockerfile that I used to do this locally, it may be valuable to others (or if someone wants to PR it back into master):

```
FROM ubuntu:18.04

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

RUN apt-get -qy update && \
    apt-get -qy install python3-pip python-dev build-essential && \
    pip3 install safety && \
    apt-get -qy clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /tmp/*

ENTRYPOINT ["/usr/local/bin/safety"]
```

Then you can simply run a command as per the README.md, like so:

`echo "insecure-package==0.1" | docker run --rm docker-pyup-safety check --stdin`

**Comment by pawamoy** [comment]
Why not

```
FROM python:3.6
RUN pip install safety
ENTRYPOINT ["/usr/local/bin/safety"]
```
?

**Comment by o6uoq** [comment]
@pawamoy that works too, but I prefer using Ubuntu over Alpine for both personal preference and security reasons.

**Comment by pawamoy** [comment]
@o6uoq The official Python images are by default based on Debian Stretch, not Alpine. To use Alpine it would have been `python:3.6-alpine` :slightly_smiling_face:

**Comment by o6uoq** [comment]
@pawamoy no worries, both work! :)

**Comment by o6uoq** [comment]
@pawamoy no worries, down to personal preference and requirements. However, I've just used `FROM python3.6` vs the Ubuntu Dockerfile snippet above:

```
REPOSITORY                                 TAG                 IMAGE ID            CREATED              SIZE
test                                       latest              3465fa621795        About a minute ago   931MB
docker-pyup-safety                         latest              c950e11944b6        20 hours ago         473MB
```
Using Ubuntu is about half the size, but again, down to your personal preference and requirements!

**Comment by pawamoy** [comment]
Ah, indeed half the size is neat. Didn't know that :slightly_smiling_face: Of course it's up to you, I was just asking! Thanks for the info

**Comment by o6uoq** [comment]
No worries! 👍
