### ISSUE TITLE
Add --proxy= command line option

### ISSUE THREAD

**Issue by GadgetSteve** [pyupio/safety#157]
* safety version: 1.8.4
* Python version: All
* Operating System: All

### Description

Trying to run safety within a corporate, _(paranoid),_ environment.
A lot of error print out about socket timeout, etc., then error termination. 

### What I Did
`pip install safety`  # N.B. pip.ini contains a proxy setting that allows it to work
`safety check`  # Resulted in the errors above
`set HTTPS_PROXY=` _the_proxy_from_pip.ini_
`safety check`  # This time it worked.
```
Not permitted to paste from company machine!
```
The underlying `requests` library has `--proxy` option that can be used to address this problem but it is not exposed by the `safety` command line.  While the work around is simple enough a lot of people who should be running `safety check` would not be happy about using it and possibly not aware - if the help for safety exposed a `--proxy=` then it should point them in the correct direction.

**Comment by chowmean** [comment]
Here is a version you can use.. 
[Adding proxy support](https://github.com/pyupio/safety/pull/161)

**Comment by Jwomers** [comment]
@chowmean thank yo for your patience, #161 is now merged. 💯
