### ISSUE TITLE
`safety check --bare` should not produce output when no vulnerabilities are found

### ISSUE THREAD

**Issue by bac** [pyupio/safety#158]
* safety version: 1.8.4
* Python version: 2.7.5
* Operating System: CentOS

### Description

Attempting to use `safety check --bare` in a cronjob expecting output and email only if vulnerabilities are seen.

Unfortunately the --bare option renders an empty string which still produces a blank line which means cron will generate email even when no vulnerabilities are seen.

### What I Did

```
MAILTO="my email address"
15 12 * * * safety check --bare
```

### Work-around

In order to get the behavior I needed, I had to write a small shell script to check the status code of running `safety check` and deliver the output when it was non-zero. While this works, `safety check` should be made to work directly in cron.

**Comment by chowmean** [comment]
Created a PR for this issue, please review if it is helpful and tell me if any problems. Thanks
[Pull Request](https://github.com/pyupio/safety/pull/159)

**Comment by rafaelpivato** [comment]
Fixed with this line specifically: https://github.com/pyupio/safety/pull/159/files#diff-dd9229c2c5d9af0b412c58e591793108R73
