### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-79: ordinal not in range(256)

### ISSUE THREAD

**Issue by bmoe872** [pyupio/safety#166]
* safety version: 1.8.4
* Python version: 3.6.6
* Operating System: Ubuntu 18.04

### Description

I installed safety using `pip install safety` and then ran: `safety check` and was met with the error in the title.

### What I Did

```
pip install safety
safety check
```

**Comment by rafaelpivato** [comment]
Are you still getting this? If so, can you please share the stack trace?

**Comment by bmoe872** [comment]
I went to something else after submitting this ticket, and I'm honestly not even sure what project I was running this on. I just installed and ran the command following the same steps I outlined, and I was not able to reproduce the issue. 

Not sure what I was getting at 1.5 years ago.

**Comment by rafaelpivato** [comment]
Thanks for your time and your patience going through this again.
