### ISSUE TITLE
Question: <= meaning

### ISSUE THREAD

**Issue by Richardwan7** [pyupio/safety#175]
* safety version: 1.8.4
* Python version:
* Operating System: Ubuntu 16.04

### Description
Does '<=' in affected version means that the latest version is affected?

### What I Did

```
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```

**Comment by Jwomers** [comment]
Hi @Richardwan7. `<=` in affected versions means that version number and lower are affected (inclusive). 
For example. <=2.0.10 means version 2.0.10 is affected.
