### ISSUE TITLE
Upgrade to click>=7.0

### ISSUE THREAD

**Issue by shivank1234** [pyupio/safety#179]
* safety version:NA
* Python version:NA
* Operating System:NA

### Description
It would be good if we use the latest release of the click package that will enable better functioning of other repo's who are using safety as a dependency

### What I Did

```
NA
```

**Comment by rafaelpivato** [comment]
Click 7 and up is being used now.

https://travis-ci.org/github/pyupio/safety/jobs/666031934#L225
