### ISSUE TITLE
Include Risk Severity in Safety Finding Details

### ISSUE THREAD

**Issue by pdmayoSFI** [pyupio/safety#197]
* safety version: 1.8.4
* Python version: 2.7
* Operating System: Ubuntu Bionic

### Description

* **Issue**: Finding details reported by Safety do not include a measure of Risk Severity rating or categorization. (i.e. Critical, High, Medium, Low, Informational)

* **Impact**: The lack of a Risk Severity rating impacts the effectiveness of a user in determining a quick priority list regarding which findings should be reviewed first from a given scan set. Lack of a Risk Severity rating additionally impacts incorporation with Vulnerability Management tools (i.e. [Defect-Dojo](https://github.com/DefectDojo/django-DefectDojo)) from presenting an accurate view of a product's vulnerability health. In Dojo's case, all findings are currently added as "Informational" due to the lack of a Risk Severity rating, as seen in [django-DefectDojo PR#848](https://github.com/DefectDojo/django-DefectDojo/pull/848). 

* **Undesirable Workaround**: An argument can be made that findings can be compared against the [safety-db](https://github.com/pyupio/safety-db/blob/master/data/insecure_full.json) to map to CVEs and then compare against NIST NVD or vFeed to obtain a Risk Severity rating. However, this is an undesirable workaround as it does not address all Safety findings. Many include `null` as the cve value and can not be mapped to a CVE for a Risk Severity rating. There are currently 868 findings in safety-db, 610 of these do not have any CVE listed and therefore can not be mapped to a Risk Severity rating in any automated fashion.

**Comment by yeisonvargasf** [comment]
Hi @pdmayoSFI, thanks for reported this, at the moment `safety` with `--full-report` option shows the severity rating (For CVEs and own PyUp vulnerabilities too) using the CVSS framework. If you want to be able to get the data, it requires a subscription (a KEY will be needed in the Safety CLI).

I'm going to close this issue, as it's solved.
