### ISSUE TITLE
Should this project contain/support a GitHub Action for safety ci?

### ISSUE THREAD

**Issue by cclauss** [pyupio/safety#198]
Should this project contain the code for a simple yet flexible GitHub Action that allows repo maintainers to quickly add automated safety testing on all pull requests submitted to their repos?

Putting that code into this repo or another pyup repo will focus development efforts on a single, community-supported GitHub Action for safety instead of a multitude of homegrown solutions.

Currently you must be in the GitHub Action beta to be able to use Actions.

https://github.com/cclauss/GitHub-Action-for-pyup-Safety-CI

**Comment by dylanpulver** [comment]
Hi @cclauss,

Thank you for your suggestion and for your patience as we reviewed it.

We appreciate the idea of having a dedicated GitHub Action for Safety CI. We currently offer a GitHub Action that allows repository maintainers to add automated safety testing to their repositories. You can find more details about our GitHub Action in the [documentation](https://docs.safetycli.com/safety-docs/installation/github-actions).

While your proposed action is valuable, we believe consolidating efforts into a single, community-supported GitHub Action will provide the most streamlined and robust solution for all users. If you have specific features or improvements in mind, we would love to hear about them and see how we can integrate them into the existing action.

Thank you for your contribution and for helping us improve Safety!

Best Regards,
The Safety Team

**Comment by cclauss** [comment]
Nice.  Closing as done.
