### ISSUE TITLE
[feature request] allow passing in output of `pip freeze`

### ISSUE THREAD

**Issue by Roguelazer** [pyupio/safety#2]
It would be cool if we could use this tool without having to install it (and its dependencies) into a virtualenv. I'm thinking something like `/path/to/questionable/virtualenv/bin/pip freeze | safety check --stdin`. Thoughts?

**Comment by dveeden** [comment]
Maybe just parse and check the `requirements.txt`?

**Comment by Roguelazer** [comment]
That wouldn't necessarily pick up transitive dependencies. 
-- 
James Brown,
currently mobile

**Comment by jayfk** [comment]
I think `--stdin` is the way to go here. This let's you read everything that fits into a pipe.

```
cat requirements.txt | safety check --stdin
/venv/pip freeze | safety check --stdin
echo "insecure-package==0.1" | python -m safety check --stdin
```

Make sure to upgrade to `0.3.0` and check it out.

**Comment by Roguelazer** [comment]
Thanks! Works perfectly!
