### ISSUE TITLE
Safety does not recognize `msgpack-python` is the same as `msgpack`

### ISSUE THREAD

**Issue by margaretgorguissian** [pyupio/safety#205]
* safety version: 1.8.5
* Python version: 3.6.0
* Operating System: Ubuntu 14.04

### Description
Safety reports a vulnerability for `msgpack` versions `<0.6.0`. However, for versions `0.5.0`, `msgpack` could be installed as `msgpack-python`. If `msgpack-python` is pinned to a version `<0.6.0`, no vulnerability is recognized.

This could be a matter of expanding the Safety DB or simply stripping `-python` from package names in preprocessing.

**Comment by rafaelpivato** [comment]
Interesting problem. I am not sure whether this is a Safety, dparse or Safety-DB issue. I bet there are more of such cases indeed. :thinking:

**Comment by dylanpulver** [comment]
Hi @margaretgorguissian,

Thank you for bringing this issue to our attention.

After careful consideration, we've decided to move this issue to the "wontfix" category. We wanted to provide some context for our decision:

Scope and Complexity: Addressing the issue of recognizing msgpack-python as the same as msgpack involves significant complexity. There are potentially many such cases, and ensuring comprehensive coverage would be challenging.

Current Priorities: While this is an important issue, it is not currently a top priority on our development roadmap. We are focusing on other enhancements that we believe will have a broader impact on our user base.

Future Considerations: We recognize the importance of accurately identifying package names and versions. We will keep this in mind for future updates and improvements to Safety and our Safety DB.

We appreciate your understanding and thank you for your valuable feedback. If you have any further suggestions or insights, we would love to hear from you.

Thank you for your continued support and contributions!

Best regards,

The Safety Team
