### ISSUE TITLE
Support requirements.txt with --hash

### ISSUE THREAD

**Issue by charleswhchan** [pyupio/safety#227]
* safety version: 1.8.5
* Python version: 3.6.7
* Operating System: Ubuntu 18.04

### Description

`safety` skips package(s) with `--hash` inside `requirements.txt`
```
$ cat requirements.txt
flask==0.12.1 --hash=sha256:6c3130c8927109a08225993e4e503de4ac4f2678678ae211b33b519c622a7242
```
### What I Did

```
$ safety check -r requirements.txt
│ REPORT                                                                       │
│ checked 0 packages, using default DB                                         │
```

If I remove `--hash`, then `safety` will process and check the package(s) as expected

**Comment by rafaelpivato** [comment]
Thanks for reporting this :+1:
