### ISSUE TITLE
Is Safety DB installed by default ? 

### ISSUE THREAD

**Issue by nikhilgeo** [pyupio/safety#249]
I like to get some clarity on few things to start using this one.

1. When installing the `safety` does it install the safety db also ?
2. When a new update happen in safety db how can my local version of safety db be updated ? Do I have to install/update safety again ?

**Comment by rafaelpivato** [comment]
1. It is not installed, but accessed remotely.
2. You don't need to update Safety to have access to new open database we publish every month.
