### ISSUE TITLE
Pythonic and Friendly API to run check

### ISSUE THREAD

**Issue by maaaaz** [pyupio/safety#251]
Hello there,
First, let me thank you for this awesome and promising project !

You already provide different ways to interact with `safety` but the most obvious one is missing: a Python module with actual bindings that can be called from another Python script.

Cheers.

**Comment by rafaelpivato** [comment]
Thanks, @maaaaz 

Have you ever look into `safety.safety` module? Maybe we need to document that better, but that's how you could use Safety from another Python script.

**Comment by Spenhouet** [comment]
I got confused here too so just as a note:

I did expect the following to work similar to `safety check`:

```
from safety import safety:
safety.check()
```

But the check methods requires all of these parameters: `packages, key, db_mirror, cached, ignore_ids, proxy` and does not collect these or have defaults like the `safety check` execution does.

Maybe that is also what @maaaaz was missing.

**Comment by rafaelpivato** [comment]
True story, @Spenhouet - I think we might need to deviate from **click** maybe, or just add a better layer in-between.

**Comment by dylanpulver** [comment]
Hi @maaaaz,

Thank you for your kind words and for suggesting this enhancement.

After careful consideration, we've decided to move this issue to the "wontfix" category. We wanted to provide some context for our decision:

Scope and Priorities: Developing a fully Pythonic and friendly API for running checks is a significant task and is currently beyond the scope of our immediate development priorities. We are focusing on other enhancements that we believe will have a broader impact on our user base.

Existing Module: We do have the safety.safety module, which can be used to run Safety from another Python script. While we acknowledge it may not be as user-friendly as desired, it provides the necessary functionality for integration.

Documentation: We agree that better documentation could help users leverage the existing module more effectively. We will consider improving the documentation to make it clearer how to use Safety from within a Python script.

We appreciate your understanding and thank you for your thoughtful feedback. If you have any further suggestions or insights, we would love to hear from you.

Thank you for your continued support and contributions!

Best regards,

The Safety Team
