### ISSUE TITLE
Can't install safety for python2 and python3 properly.

### ISSUE THREAD

**Issue by dveeden** [pyupio/safety#3]
- safety version: 0.2.2
- Python version: 2.7.12 and 3.5.1
- Operating System: Fedora 24
### Description

Installing safety not in a venv, but on the system for both python2 and python3 results in the /usr/bin/safety file to be overwritten
### What I did

```
pip install safety
pip3 install safety
```

The hashbang contains the python version for which safety was last installed.

**Comment by jayfk** [comment]
I don't know if there's a way around this. Do you have any information about what `/usr/bin/safety` does in fedora?

**Comment by jayfk** [comment]
I've just installed safety in a fresh Fedora 24 VM and couldn't reproduce the problem.

**Comment by jayfk** [comment]
I wasn't able to reproduce this.
