### ISSUE TITLE
Guidance on licensing this tool

### ISSUE THREAD

**Issue by ASVincent** [pyupio/safety#301]
* safety version: N/A
* Python version: N/A
* Operating System: N/A

### Description

From this repository I don't have a clear idea of the license of using the updated-once-a-month cli implementation provided by this repository. This repository is licensed as MIT, but the dataset that it uses is licensed as non-commercial only (If I read it correctly).

It'd be great to have a few common uses cases that are permitted by use of these tools and use cases that must have a license for the dataset to help give those evaluating the library greater clarity without needing to engage a lawyer for appropriate licensing in common scenarios.

Use in:
* Open source projects
* Government and/or NPO/NGOs
* Personal Use (I assume the preference here is licensed unless open source?)

If this is asking too much feel free to close this request, but any general guidance/information that you provide over email replicated here but targetting this implementation would be appreciated.

Thanks for contributing these resources to the open-source community; they are a great help in evaluating and reviewing packages for use :)

### What I Did

Trying to do: Evaluate safety for use in a project.
Clicked on the website and read the pricing/licensing page.

**Comment by harlekeyn** [comment]
Hello @ASVincent,

Aside from what is written in [our FAQ](https://pyup.io/help/faq/), we can discuss an ad hoc license in special cases. Please reach out to us by email to discuss your specific situation: support@pyup.io.

I can see your point of also giving licensing details about various atypical scenarios, but we presently do not have that list available..

Tristan
