### ISSUE TITLE
"Unable to load vulnerability database"

### ISSUE THREAD

**Issue by Spenhouet** [pyupio/safety#307]
* safety version: 1.9.0
* Python version: 3.7
* Operating System: Windows 10

### Description

Savety does not work and only outputs "Unable to load vulnerability database".

Maybe this is just a temporary issue (or something local?).
If this is not an issue for anyone else, then please point that out and just close this issue.

**Comment by Spenhouet** [comment]
It now only works sporadically.

**Comment by Spenhouet** [comment]
It seems to work again.

**Comment by harlekeyn** [comment]
Hello @Spenhouet / Sebastian.

Our service was down twice for less than a minute yesterday. We were also down for a third time, and this was for about one full minute. It could be that you were trying to access our service exactly at those moments, or perhaps there indeed was some local issue for you.

In any case, I'm glad to see that everything is working again for you now.

Tristan
