### ISSUE TITLE
Add environment variable for ignoring some checks

### ISSUE THREAD

**Issue by EugeniuZ** [pyupio/safety#323]
* safety version: 1.8.1
* Python version: 3.7.5
* Operating System: Ubuntu 18.04

### Description

It would be handy to be able to disable globally some checks. 
My use case: I have a Bamboo server that runs the safety checks on multiple projects. Whenever there is a check I want to ignore I have to add the exception to each project (with `-i <number>`). It would be handy to define an environment variable so i can disable the check for particular vulnerabilities globally for all projects.

**Comment by harlekeyn** [comment]
Added to our wish list. Thanks, @EugeniuZ
