### ISSUE TITLE
When will the pyupio/safety:latest Docker image be updated to latest version?

### ISSUE THREAD

**Issue by pzelnip** [pyupio/safety#333]
### Description

Safety 1.10.1 is now out, but it appears that the `pyupio/safety:latest` Docker image on Dockerhub is still 1.9.0:

```
$ docker run --rm pyupio/safety safety --version
Unable to find image 'pyupio/safety:latest' locally
latest: Pulling from pyupio/safety
6ec7b7d162b2: Pull complete 
80ff6536d04b: Pull complete 
0371261f6d81: Pull complete 
51dcc7f0b98f: Pull complete 
f7da8c5f5270: Pull complete 
a3fa580b2b50: Pull complete 
Digest: sha256:c0b61ce5be48a2189d706b6768042933a2d3d952747c08311348514df44ee623
Status: Downloaded newer image for pyupio/safety:latest
safety, version 1.9.0
```

When will the image on Dockerhub be updated with v1.10?

**Comment by dylanpulver** [comment]
![Image](https://github.com/user-attachments/assets/1c6e62a1-9531-4a19-9de3-9db383e5cba4)

Hi @pzelnip,

Thank you for your patience and for bringing this to our attention.

We're pleased to inform you that the pyupio/safety:latest Docker image has been updated and now includes the latest version of Safety, which is 1.10.3.

If you encounter any issues or have further questions, please let us know.

Thank you for your continued support!

Best Regards,
The Safety Team
