### ISSUE TITLE
Confusing "Development status" (pre alpha) on pypi.org?

### ISSUE THREAD

**Issue by dr47** [pyupio/safety#339]
* safety version: all
* Python version: all
* Operating System: all

### Description

Pre-Alpha development status is displayed in pypi.org. 
It is true?
If not, is it possible to correct the status?
It yes, do you plan to stabilize safety for use in a production environment? (status = stable) 

### What I Did

```
I viewed the page: https://pypi.org/project/safety/
```

**Comment by damiencarol** [comment]
it's because of this line https://github.com/pyupio/safety/blob/55cc69d40418424d4fdb776963dbf48ed2f7fa4f/setup.py#L45

**Comment by damiencarol** [comment]
@yeisonvargasf do you accept PR? I can have few proposal to improve this part (not only some flags)

**Comment by adiroiban** [comment]
Also if handling this, maybe  in setup.cfg also remove the universal build as only py3 is supported.

https://github.com/pyupio/safety/blob/55cc69d40418424d4fdb776963dbf48ed2f7fa4f/setup.cfg#L2

Right now the download file is named `safety-1.10.3-py2.py3-none-any.whl `

**Comment by yeisonvargasf** [comment]
sorry late answer, PRs are welcome.

**Comment by yeisonvargasf** [comment]
We have already fixed this issue. Thank you all.
