### ISSUE TITLE
App Broken due to breaking Changes

### ISSUE THREAD

**Issue by chandanch** [pyupio/safety#342]
* safety version: 1.10.3
* Python version: 3.6
* Operating System: Ubuntu 20.4

### Description

Pin werkzeug library to 1.0.1 version since there are breaking changes in that version and which is breaking the applications.

### What I Did
Upgrading werkzeug to 2.0.0 is breaking the application. Please specify the version to 1.0.1

**Comment by yeisonvargasf** [comment]
Hi @chandanch, could you please post more info related to the error thrown by safety? also, how are you using safety (which command are you using)?
