### ISSUE TITLE
`--bare` and `--full-report` should be mutually exclusive

### ISSUE THREAD

**Issue by sobolevn** [pyupio/safety#346]
I ran into this problem way too often 🙂 

Like here: https://github.com/wemake-services/docker-image-size-limit/blob/4b9a9c690d6b4ce2d90419ac9bed13f6898659af/.github/workflows/test.yml#L48

I propose to make `--bare` and `--full-report` CLI options for `check` command mutually exclusive. So, passing `safety check --bare --full-report` would result in `ArgumentError`. Right now it fallbacks to `--bare`.

**Comment by yeisonvargasf** [comment]
Thanks for the report @sobolevn; `Safety >= 2.0.0` fixes this issue.
