### ISSUE TITLE
Could you update python version in dockerfile ?

### ISSUE THREAD

**Issue by cedric-orange** [pyupio/safety#357]
### Description

Python version in docker is actualy 3.6, as you know python 3.6 is eol in 2 months : https://endoflife.date/python
Could you build a new version of this container with an updated python version.

**Comment by yeisonvargasf** [comment]
Hi @cedric-orange, the dockerfile has been updated. On the other hand, a new Github action will be published soon, and there is the new Safety 2.0 version; you can take a look at the latest beta [2.0b5](https://pypi.org/project/safety/2.0b5/)
