### ISSUE TITLE
Fails when there is any package info from git.

### ISSUE THREAD

**Issue by chowmean** [pyupio/safety#38]
* safety version: Latest 
* Python version: 2.7 
* Operating System: MACOS

### Description

I was try to run safety and it fails cause there were entries which contains something like 'git+git...'
in requirements.lock 

```
Expected version spec in git+git://github.com/*** at +git://github.com/***
```

### What we can do
We can put the version check in try catch maybe.

**Comment by jayfk** [comment]
This should be fixed in https://github.com/pyupio/safety/commit/f51f05b08842c9ce4322d05d644500dbb8458673. Could you try to update safety to the latest release and run it again?
