### ISSUE TITLE
Support HTML report

### ISSUE THREAD

**Issue by princeBzik** [pyupio/safety#388]
* safety version: 1.10.3
* Python version: 3.6.8
* Operating System: macOS/centos

### Description

An HTML report with the finding will be very helpful

**Comment by insider89** [comment]
Yeah, would be great to support output in html format.

**Comment by yeisonvargasf** [comment]
It would be nice to have this feature; probably it will be added in Safety 2.1

**Comment by chowmean** [comment]
@yeisonvargasf what is the status of this? Is someone working on it? I want to contribute to this if there is a possibility. Thanks!

**Comment by yeisonvargasf** [comment]
Hi @chowmean, It's in the roadmap, but there are other reports and features with higher priority; we are looking for more integration with other platforms, so the team is putting all the effort into those and other relevant features.

It would be great if you could send a PR for this feature (Thanks!); I'll review it and allow merging it in a quicker way possible.

**Comment by chowmean** [comment]
sure, please assign this to me.

**Comment by yeisonvargasf** [comment]
Thanks to @chowmean for the contribution!
