### ISSUE TITLE
Is 2.0 out or not?

### ISSUE THREAD

**Issue by pzelnip** [pyupio/safety#390]
### Description

I have safety as a dependency tracked by pyup on this repo: https://github.com/pzelnip/depwatch/pull/459

Today it opened a PR saying to upgrade safety to 2.0.

2.0 appears to be released on Pypi: https://pypi.org/project/safety/2.0.0/

2.0 does not appear to be released looking at the release history: https://pyup.io/changelogs/safety/ or https://github.com/pyupio/safety/releases

Is 2.0 final now officially released and safe to use, or is this an error/accidentally uploaded to pypi by mistake?

**Comment by yeisonvargasf** [comment]
Hi @pzelnip,

2.0 was planned, but the changelog page has a bug, and we will fix it soon.

The most recent version is 2.1.1.
