### ISSUE TITLE
Used as dependency?

### ISSUE THREAD

**Issue by pawamoy** [pyupio/safety#401]
In the changelog of release 2.0, you say:

> Now Safety can be used as a dependency in your code

What does this mean exactly?

**Comment by yeisonvargasf** [comment]
Hi @pawamoy,

In the beginning, PyUp created Safety to be only a CLI tool, but a group of users was using Safety as a dependency in their code; importing Safety in your code wasn't officially supported then.

In Safety >=2.0, we ensured that users could use Safety directly in the code. So now we keep CLI commands and the internal API following SEMVER.

If you have more questions, please create a new issue. I'll close this for now.

**Comment by pawamoy** [comment]
That answers my question, thank you 🙂
