### ISSUE TITLE
Documentation for GitHub action seems out of date

### ISSUE THREAD

**Issue by jlaine** [pyupio/safety#402]
The documentation currently states that the GitHub action can be used with:

```yaml
uses: pyupio/safety@v1
```

However this leads to the following error:

```
Error: Unable to resolve action `pyupio/safety@v1`, unable to find version `v1`
```

AFAICT the documentation should be updated with

```yaml
uses: pyupio/safety@2.0.0
```

See:
- https://docs.pyup.io/docs/github-actions-safety
- https://github.com/marketplace/actions/pyupio-safety

**Comment by yeisonvargasf** [comment]
Thanks for reporting this, @jlaine. We updated the documentation.
