### ISSUE TITLE
safety action version 2.0.0 is broken

### ISSUE THREAD

**Issue by rbarrois** [pyupio/safety#417]
* safety version: 2.0.0
* Python version: N/A
* Operating System: Github Actions

### Description

We run the pyupio/safety Github Action as described here: https://docs.pyup.io/docs/github-actions-safety#step-3-configure-your-github-workflow-yaml-file-to-run-safety-scans

That action relies on the [*latest* docker version from safety](https://github.com/pyupio/safety/blob/40fb27ab528d8a62fdb91999b11b0037381c7d07/action.yml#L53); however, when said version requires new parameters, the related action is not kept up-to-date, and crashes.

### What I Did

We defined the action as:

```yaml
- uses: pyupio/safety@2.0.0
  with:
    api-key: *** 
    scan: file
    requirements: requirements.txt
```

And got the following error:
```sh
/app/entrypoint.sh: line 69: SAFETY_ACTION_CREATE_PR: unbound variable
```

### Suggested fix

I think safety should implement one of the following patterns:

- Run integration tests, ensuring that past versions of the action don't crash;
- Communicate with its customers when old versions of its Github Actions are deprecated and should no longer be used;
- Provide a clear error message when the Docker container fails on invalid error message (e.g. "Please update to `pyupio/safety@2.x.y`")

Thanks!

**Comment by yeisonvargasf** [comment]
Hi @rbarrois, thank you for the detailed report!

You are right; I updated the image with a fix to handle the old versions of the GitHub action.

> Run integration tests, ensuring that past versions of the action don't crash;

I implemented regression tests, so we can monitor if new features will break the old versions of the GitHub action.

> Communicate with its customers when old versions of its Github Actions are deprecated and should no longer be used;

I communicated this to our internal team.

> Provide a clear error message when the Docker container fails on invalid error message (e.g. "Please update to pyupio/safety@2.x.y")

Working on this too, it's in the roadmap.

This issue should be fixed, please let me know if all is good from your side and I'll close this issue. Happy to help!

**Comment by yeisonvargasf** [comment]
@rbarrois, I'm closing this; feel free to open a new one if you find something still isn't working fine.

Thank you for the issue report!
