### ISSUE TITLE
--full-report is a noop on master

### ISSUE THREAD

**Issue by ktosiek** [pyupio/safety#42]
* safety version: master (3b37e2543e476c5b3e8701fd5a0b5a779701beb5)
* Python version: Any
* Operating System: Any

### Description

Even though it's still in --help, it looks like --full-report argument is ignored, and there's no way on master to show additional information about vulnerabilities found. Is that intentional? Is the option to see details of vulnerabilities going to be removed?

**Comment by jayfk** [comment]
Yep, this isn't working on master.

The master database will get a big update next week and will include advisories and proper IDs. Once that's done using the --full-report option will spit out advisories :)

**Comment by ktosiek** [comment]
Yay! I wanted to look at fixing #22, but that bug probably went away with old full report :-)

**Comment by jayfk** [comment]
Full report is back again: https://github.com/pyupio/safety/commit/cfedd9cf93d88291ef94c73a08f8a324b85fb5ef
