### ISSUE TITLE
 safety requires py > 1.11.0 which hasn't been released yet

### ISSUE THREAD

**Issue by NikolaKikovski** [pyupio/safety#421]
* safety version: `2.3.1`
* Python version: `3.10.8`
* Operating System: `macOS 13.0`

### Description
`safety` currently requires [py > 1.11.0](https://pypi.org/project/py/) for its checks to pass (see screenshot) with ID 51457:
<img width="638" alt="изображение" src="https://user-images.githubusercontent.com/42459611/199703500-ce2a74ec-4e01-4fac-9a36-b2b277722008.png">

but `py` has no newer versions

### What I Did

```
safety check --file=requirements.txt
```

**Comment by yeisonvargasf** [comment]
Hi @NikolaKikovski,

That image isn't the default UI in Safety `2.3.1`. Could you attach a screenshot with the output of the following command:  `safety --version`

Related to the vulnerability, you should report that in the repo for the database: https://github.com/pyupio/safety-db/issues. @SCH227 can help you there.

**Comment by yeisonvargasf** [comment]
Feel free to open a new issue with more detailed information.
