### ISSUE TITLE
Bare output includes extra line in non-screen output with no vulnerabilities

### ISSUE THREAD

**Issue by chris-bradley** [pyupio/safety#423]
* safety version: 2.3.1
* Python version: 3.6 and later
* Operating System: Linux

### Description

When running `safety` with `--output bare` in an environment with no vulnerabilities in a non-screen environment (eg. within a cron task or piping to a file), a single line is output:
`+==============================================================================+`
When used as a cron task, this causes an unnecessary email to be sent.

### What I Did
Within a cron environment:
```
>>> safety check --output bare
+==============================================================================+
```
Due to the un-needed output, an email is sent.

**Comment by yeisonvargasf** [comment]
@chris-bradley, as a workaround, you should be able to redirect `stderr`. Let me know if that helps.
