### ISSUE TITLE
LegacyVersion dropped of the package packaging

### ISSUE THREAD

**Issue by carlosdorneles-mb** [pyupio/safety#437]
* safety version: 2.3.3
* Python version: 3.10.8
* Operating System: macOS

### Description

In the most current version of the Safety package, the LegacyVersion function of the [Packaging](https://github.com/pypa/packaging/releases/tag/22.0) package is being used and starting from version 22 of Packaging, this has been removed.

### What I Did

When running the command on github CI it is raising the error `cannot import name 'LegacyVersion' from 'packaging.version'`

![image](https://user-images.githubusercontent.com/87037175/206324140-8f659138-ae3d-4733-9c69-fb5b1c40fa9e.png)

**Comment by Jwomers** [comment]
Hi @carlosdorneles-mb we're working on a fix for this asap, and should have it done in the next few hours or sooner. We'll keep you updated. cc @DragosChirila

**Comment by yeisonvargasf** [comment]
I'm closing this because [Safety 2.3.4](https://pypi.org/project/safety/2.3.4/) is available in `PyPI` with a fix for this issue; thank you for the report @carlosdorneles-mb and @DragosChirila!
