### ISSUE TITLE
Distro backports considered?

### ISSUE THREAD

**Issue by buhtz** [pyupio/safety#450]
How does safety identify the version of a package?
Does it take into account that it might be "old" but have security fixes backported by the distro maintainers. This happens often at Debian for example. The package version might by old (e.g. 2.1) but it does have security fixes provided by upstream in the a newer version only (e.g. 2.6). But the distro maintainers do take such fixes and backport them to their old version.

Does safety notice this?

**Comment by Jwomers** [comment]
Hi @buhtz! Thanks for sending this through. This is an interesting edge case that we need to handle better. Are you aware of some good examples in the Python ecosystem where we could study this and learn from? Also, do you have any ideas from your side on how we would tackle this? What repeatable process could we follow to track this, both on the patch side and separately the scanner side? Just curious to hear your thoughts :) Thanks!

**Comment by dylanpulver** [comment]
Hi @buhtz,

Thank you for bringing this important topic to our attention.

After careful consideration, we've decided to move this issue to the "wontfix" category. We wanted to provide some context for our decision:

Scope and Complexity: Handling distribution backports is a complex and nuanced task that is currently beyond the scope of Safety's capabilities. It requires significant changes to how we identify and track package versions and backported security fixes.

Future Considerations: While we recognize the importance of this feature, it is not part of our immediate development roadmap. We may explore this further in the future as we continue to enhance Safety's functionality.

We appreciate your understanding and thank you for your thoughtful feedback. If you have any further suggestions or insights, we would love to hear from you.

Thank you for your continued support and contributions!

Best regards,

The Safety Team
