### ISSUE TITLE
Provide terse output when no problems are found

### ISSUE THREAD

**Issue by arthurzenika** [pyupio/safety#457]
* safety version: v2.3.5
* Python version: 3.10
* Operating System: Ubuntu

### Description

It would be nice to have an output that provides a full-report when a vulnerability is found and a single line when no vulnerabilities are found. 

We run safety in a collection of lint tools and the output is too verbose (and contains red text when 0 vulnerabilities are found).  

### What I Did

```
safety check --full-report
```

**Comment by jl-applied** [comment]
If it helps, you can fairly trivially workaround this in shell (bash for example),
```
function run_safety_and_echo_on_failure() {
  output=$(safety check --full-repo 2>&1)
  exit_status=$?

  if [ $exit_status -ne 0 ]; then
    echo "$output"
  fi
}
```

**Comment by dylanpulver** [comment]
Hi @arthurzenika,

Thank you for your suggestion and for bringing this issue to our attention.

After careful consideration, we've decided to move this issue to the "wontfix" category. We wanted to provide some context for our decision:

Community Preferences: Output formatting can be highly subjective, and it's challenging to measure if there is a broad demand for a terse output format. We aim to balance the needs of our diverse user base.

Workaround Available: As noted by @jl-applied, there is a simple workaround that users can implement to achieve the desired output format. This can help manage verbosity while we continue to focus on other enhancements.

We appreciate your understanding and encourage you to share any further suggestions or feedback. Your input is invaluable as we continue to improve Safety and make it more user-friendly.

Thank you for your continued support and contributions!

Best regards,

The Safety Team
