### ISSUE TITLE
Feature: Suppress ignored vulnerabilities

### ISSUE THREAD

**Issue by andy-maier** [pyupio/safety#462]
### Description

If vulnerabilities have to be ignored for some reason (e.g. because the fixed version of the dependent package can only be used on a subset of Python versions), the report of the current version of safety still reports them. That lets any newly found vulnerabilities "drown" amongst all the ignored vulnerabilities.

I suggest that a policy file parameter gets introduced that controls whether or not ignored vulnerabilities are included in the report.

**Comment by dylanpulver** [comment]
Hi @andy-maier,

Thank you for your suggestion and for bringing this issue to our attention.

After careful consideration, we've decided to move this issue to the "wontfix" category. We wanted to provide some context for our decision:

Complexity: Implementing a feature to suppress ignored vulnerabilities in the report is a complex task. It requires significant changes to our reporting structure and logic.

Current Priorities: While we recognize the value of such a feature, it is not currently a top priority in our development roadmap. We are focusing on other enhancements that we believe will benefit a larger segment of our users.

We appreciate your understanding and encourage you to continue sharing your valuable feedback. Your input is crucial as we work towards improving Safety and making it more user-friendly.

Thank you for your continued support and contributions!

Best regards,

The Safety Team
