### ISSUE TITLE
Feature: Table output

### ISSUE THREAD

**Issue by andy-maier** [pyupio/safety#463]
### Description

Earlier versions of safety had a table output. That was very good to consume.

The current report format is too verbose. The --short-format option also does not solve that, because it just truncates the explanation (making it pretty useless) without condensing the output format in any way.

Can we get back the table output?

**Comment by dylanpulver** [comment]
Hi @andy-maier,

Thank you for your feedback and for highlighting the value of the table output format.

After careful consideration, we've decided to move this issue to the "wontfix" category. We'd like to provide some context for our decision:

Current Priorities: While we understand that the table output was useful for many users, reintroducing it is not currently part of our development priorities. We are focusing our efforts on other areas that we believe will have a broader impact on the user experience.

Output Format: We appreciate your feedback regarding the verbosity of the current report format and the limitations of the --short-format option. We are always looking for ways to improve and streamline our output formats.

We appreciate your understanding and encourage you to share any further suggestions or feedback you might have. Your input is invaluable as we continue to evolve and enhance Safety.

Thank you for your continued support and contributions!

Best regards,

The Safety Team
