### ISSUE TITLE
What happened to check 37771?

### ISSUE THREAD

**Issue by tucked** [pyupio/safety#469]
What happened to https://pyup.io/v/37771/742?
This shows up in a run from a little over a month ago but it doesn't anymore (and I haven't changed the version of Django I'm checking) 🤔

**Comment by Jwomers** [comment]
Hi, I had a quick look at our database and it seems that vulnerability was
marked as invalid, marked as a duplicate for this vulnerability:
https://pyup.io/v/37661/742/

**Comment by tucked** [comment]
Aha! Makes sense, thank you 👍 (Also makes sense why I'm not seeing it anymore, since I'm checking Django 1.10.5, and 37661 notes that the min affected version is 1.11a1.)
