### ISSUE TITLE
Add Pipfile support

### ISSUE THREAD

**Issue by jayfk** [pyupio/safety#47]
Safety already works with the currently active virtual environment, but it would be nice to to run:

```
safety check -r Pipfile
```
or

```
safety check -r Pipfile.lock
```

It's probably the best to wait for https://github.com/pypa/pipfile/pull/57 before working on this.

**Comment by katzdm** [comment]
Looks like pypa/pipfile#57 has been abandoned - Would it be worth revisiting this under that assumption, or was that PR an absolute blocker?

**Comment by gtsop** [comment]
What's the status of this?

**Comment by dylanpulver** [comment]
Hi @jayfk and everyone involved,

Thank you for your feature request and for your patience as we reviewed it.

We're pleased to inform you that Safety now supports scanning Pipfile and Pipfile.lock files directly. This feature allows users to run commands like safety scan --target /path/to/Pipfile or safety scan --target /path/to/Pipfile.lock to check for vulnerabilities in their dependencies.

If you have any further questions or encounter any issues, please let us know.

Best Regards,
The Safety Team
