### ISSUE TITLE
safety GitHub Action produces 'set-output' deprecation warnings

### ISSUE THREAD

**Issue by semuadmin** [pyupio/safety#470]
* safety version: 2.3.5
* Python version: 3.7 - 3.11
* Operating System: GitHub Actions Linux environment

### Description

The safety GitHub action produces the following deprecation warnings:
```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

NB: Following [advisory on GitHub](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/):

_"Starting today runner version 2.298.2 will begin to warn you if you use the save-state or set-output commands via stdout. We are monitoring telemetry for the usage of these commands and plan to fully disable them on 31st May 2023. Starting 1st June 2023 workflows using save-state or set-output commands via stdout will fail with an error."_

### What I Did

I added the following action to my GitHub Action workflow:
```
      - uses: pyupio/safety@2.3.5
        with:
          api-key: ${{ secrets.SAFETY_API_KEY }}
```

**Comment by yeisonvargasf** [comment]
Thank you for reporting this, @semuadmin.

There is a big coming release, and it will fix this.

**Comment by yeisonvargasf** [comment]
This should be fixed now. So I'll close the issue for now; feel free to reopen or comment if you still see the issue.
