### ISSUE TITLE
Document timeouts and make them configurable

### ISSUE THREAD

**Issue by Zeckie** [pyupio/safety#487]
* safety version: 2.3.5
* Python version: 3.12
* Operating System: Windows

### Description

Running `safety check` often results in the error `Check your network connection, the request timed out.`. It isn't clear from the output what is timing out (eg was it while establishing the connection, or waiting for a response), how long it waited before timing out, what resource it was fetching, or even what server it was connecting to. 

Also, is there a way to increase the timeout (seems to be hard coded [here](https://github.com/pyupio/safety/blob/main/safety/safety.py#L126) to 5 seconds)? I tried [searching for timeout in the documentation](https://docs.safetycli.com/safety-2/safety-cli-2-scanner/installation-and-quick-start-safety-2?q=timeout), but there were no results.

**Comment by dylanpulver** [comment]
fixed with https://github.com/pyupio/safety/pull/541

added to the safety 3 docs here: https://docs.safetycli.com/safety-docs/safety-cli-3/available-commands-and-inputs#environment-variables
