### ISSUE TITLE
Conflict with the pyjwt package

### ISSUE THREAD

**Issue by jma** [pyupio/safety#492]
* safety version: 3.0.0
* Python version: 3.9.15
* Operating System: Macosx

### Description

With the new safety version 3.0.0 a new dependency has been introduced jwt@1.3.1. This package has the same import as the pyjwt which is seems more used and has more contributors. Maybe jwt can be replaced by pyjwt.

**Comment by xalien10** [comment]
@yeisonvargasf is there any news about fixing this issue?
