### ISSUE TITLE
dependency on old pydantic causes conflicts with other packages

### ISSUE THREAD

**Issue by washeck** [pyupio/safety#495]
* safety version: 3.0.0
* Python version: 3.11
* Operating System: linux

### Description

safety 3.0.0 depends on pydantic <2, while other packages require v2 (e.g. django-qr-code depends on pydantic >2.5)

### What I Did

```
$ poetry add safety
Using version ^3.0.0 for safety
...
Because no versions of safety match >3.0.0,<4.0.0
 and safety (3.0.0) depends on pydantic (>=1.10.12,<2.0), safety (>=3.0.0,<4.0.0) requires pydantic (>=1.10.12,<2.0).
And because django-qr-code (4.0.1) depends on pydantic (>=2.5), safety (>=3.0.0,<4.0.0) is incompatible with django-qr-code (4.0.1).
```

**Comment by yeisonvargasf** [comment]
@washeck, that's correct; we expect to migrate to pydantic > 2.5 inside `safety-schemas` soon.

**Comment by washeck** [comment]
Well, until this is fixed, we cannot use `safety` because there is no way for the new and old pydantic to cooexist in one project and we cannot drop library used in our production system just because of development support tool.

I understand this is more a problem caused by `pydantic` authors, but IMHO you should consider not requiring the users of `safety` to install `pydantic`. See e.g. `jedi-language-server` changelog:

`Removed pydantic dependency; it made distributing jedi-language-server harder than it needed to be.`

**Comment by akjmicro** [comment]
Yeah, `safety` folks, this is a big one. Working here at my company on an `airflow` container ecosystem, this is only dependency causing compatibility issues ATM.

**Comment by yeisonvargasf** [comment]
Hi folks, thanks for the report here. We should get this resolved next week.

@frwickst, thanks for the hints.

@washeck, in the short term, we aren't considering dropping Pydantic, this dependency conflict will be solved soon.

**Comment by matthiaskoenig** [comment]
Thanks. Same issue here.

**Comment by yeisonvargasf** [comment]
Hi, thanks for the patience here, we will soon release an update that supports 1.x and 2.x

**Comment by yeisonvargasf** [comment]
A `safety_schemas` version `0.0.2` is available, which includes compatibility for Pydantic 1.x and 2.x.

Can you try to install Safety, Pydantic 2.x, and safety_schemas `0.0.2` with pip? Safety 3.0.1 still has the specifier for `pydantic<2.0`; we will remove it once we get some feedback from users.

**Comment by dotlambda** [comment]
@yeisonvargasf Works on [NixOS](https://github.com/NixOS/nixpkgs/pull/284703). Thanks a lot!

**Comment by Pacheco95** [comment]
@yeisonvargasf didn't work for python:3.12 container:

```
fastapi~=0.109.2
pydantic-settings~=2.1.0
```

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pydantic-settings 2.1.0 requires pydantic>=2.3.0, but you have pydantic 1.10.14 which is incompatible.
```

**Comment by sobolevbel** [comment]
```
There are incompatible versions in the resolved dependencies:
  pydantic<3.0.0,>=2.5.3 (from maison==1.4.3->autoimport==1.4.0->-r requirements/tests.in (line 33))
  pydantic<2.0,>=1.10.12 (from safety==3.0.1->-r requirements/tests.in (line 8))
  pydantic (from safety-schemas==0.0.2->safety==3.0.1->-r requirements/tests.in (line 8))
```

**Comment by FluxZA** [comment]
@yeisonvargasf  Working for us on Py 3.11

**Comment by sobolevbel** [comment]
Sorry for asking, but we're waiting for the fix. Do you know where it'll be available for everyone?

**Comment by yeisonvargasf** [comment]
The upper range limit was removed on Safety `3.1.0` version.

**Comment by RafaelWO** [comment]
Great! I believe this can be closed then, right? 🙂
