### ISSUE TITLE
Safety 3.0.1 fails to output HTML report

### ISSUE THREAD

**Issue by quoimec** [pyupio/safety#512]
* safety version: 3.0.1
* Python version: 3.10
* Operating System: Windows 11

### Description

I'm trying to run safety locally to produce an HTML report however Safety continually fails with the following error message when I use the `--output html` option:

```
Unhandled exception happened: scan/index.html
```

No other output or context is provided by the package.

### What I Did

I am running the following safety command to produce the report:
```
safety --stage production --key 'MY_KEY' scan --target SOME_DIR --output html --policy-file .safety-policy.yml
```
When I use the `--output json` option however, safety runs successfully. I am running Safety inside of an isolated Poetry environment with few other packages installed.

**Comment by SafetyQuincyF** [comment]
Hi @quoimec,

Thank you for reporting this issue!

I'm happy to let you know that this has been resolved in the latest version of Safety. 🎉 Please update to the newest version to benefit from the fix. If you encounter any further issues, feel free to reach out!
