### ISSUE TITLE
safety auth redirected to localhost:49152

### ISSUE THREAD

**Issue by caot** [pyupio/safety#514]
* safety version:     3.1.0
* Python version:   3.9.18
* Operating System: Redhat

### Description

`safety auth` launched browser and redirected to `http://localhost:49152/?code=<hashcode with a length of 82>`

### What I Did

```
`safety auth` launched browser and redirected to `http://localhost:49152/?code=<hashcode with a length of 82>`
, then posted ``` 🛑 Error logging into Safety. Please try again, or use `safety auth -–help` for more information```

```

**Comment by SafetyQuincyF** [comment]
Hi @caot,

Thank you for bringing this up!

I’ve tested safety auth with the latest version, and everything seems to be working as expected. Unfortunately, I wasn’t able to recreate the issue you described. If the problem arises again, please don’t hesitate to reach out, and we’ll look into it further.
