### ISSUE TITLE
safety auth --help throws error

### ISSUE THREAD

**Issue by Iain-S** [pyupio/safety#515]
* safety version: 3.1.0
* Python version: 3.12
* Operating System: MacOS

### Description

I would like to run the `safety auth` command with the `--help` flag to get more information about the `auth` command.

### What I Did

```bash
 safety auth --help

 Authenticate Safety CLI to perform scans. Your default browser will automatically open to
 https://platform.safetycli.com. Example: safety auth login

 Usage: safety [GLOBAL-OPTIONS] auth [OPTIONS] COMMAND [ARGS]...

Traceback (most recent call last):
...
TypeError: _print_commands_panel() missing 1 required keyword-only argument: 'cmd_len'
```

It appears that the problem call is [here](https://github.com/pyupio/safety/blob/b56a4dc89b6364594d67386bedac0524df519327/safety/cli_util.py#L106).

FYI, I think this would have easily been picked up by a linter such as pylint.

**Comment by SafetyQuincyF** [comment]
Hi @Iain-S ,

Thank you for reporting this issue!

I'm happy to let you know that this has been resolved in the latest version of Safety. 🎉 Please update to the newest version to benefit from the fix. If you encounter any further issues, feel free to reach out!
