### ISSUE TITLE
regression of `filelock` from 3.15.4 to 3.12.2

### ISSUE THREAD

**Issue by alisterd51** [pyupio/safety#551]
* safety version: 3.2.4
* Python version: 3.11
* Operating System: debian 12

### Description

Upgrading `safety` from 3.2.3 to 3.2.4 results in a regression of `filelock` from 3.15.4 to 3.12.2.
Is this limitation voluntary and justified?

**Comment by SafetyQuincyF** [comment]
Hi @alisterd51,

This issue has been resolved in my latest PR! 🎉 Please check out the latest version of Safety to see the fix in action. Let me know if you encounter any further issues!
