### ISSUE TITLE
Add minimum typer version

### ISSUE THREAD

**Issue by Iain-S** [pyupio/safety#563]
Although typer is still in 0.x.y, it would be of benefit to have a minimum version specified in setup.cfg.
This line, for example, imports `MarkupMode`, which was not in `typer.core` until `0.6.0`.

https://github.com/pyupio/safety/blob/adc0e6acc0d20f4f674ead983e8e9ceea0df4178/safety/cli_util.py#L8

Could we change setup.cfg to be

```
typer>=0.6.0
```

I'm happy to verify the exact minimum version though I guess that's subject to constant change.

**Comment by SafetyQuincyF** [comment]
Hi @Iain-S,

Thank you for your suggestion! I’ve incorporated it into my latest PR. 🎉 Let us know if there’s anything else you’d like to see improved.
