### ISSUE TITLE
Safety scan fails for PVE-2024-99889 for "requests" python package with Unhandled exception happened: Invalid specifier: '<.0.13.4'

### ISSUE THREAD

**Issue by desaintmartin** [pyupio/safety#648]
### Checklist

- [X] I agree to the terms within the [Safety Code of Conduct](https://github.com/pyupio/safety/blob/main/CODE_OF_CONDUCT.md).

### Safety version

3.2.13

### Python version

3.12.7

### Operating System

macos 15

### Describe the problem you'd like to have solved

Since update of PVE-2024-99889 (https://data.safetycli.com/vulnerabilities/PVE-2024-99889/65531/), it seems wrong specifier makes safety crash and prevent any scan if the python package requests is defined to be scanned.

### Describe the ideal solution

- fix in PVE-2024-99889 
- fix in safety preventing future crash for future errors in PVE definitions

### What I Did

Have a requirements.txt with `requests==2.32.3`
then:
```
❯ SAFETY_API_KEY=the_key safety scan
Safety 3.2.13 scanning /the/directory
2024-12-12 09:54:53 UTC

Account: API key used
 Git branch: master
 Environment: Stage.development
 Scan policy: local scan policy file

Python detected. Found 1 Python requirement file, 1 Python pyproject.toml file and 1 Python environment
Unhandled exception happened: Invalid specifier: '<.0.13.4'
```

**Comment by LouisBroekhuijsen** [comment]
We encounter the same issue, on Linux.
