### ISSUE TITLE
Check for pytosquatting packages

### ISSUE THREAD

**Issue by KangOl** [pyupio/safety#84]
`safety` is the perfect tool to check against these malicious packages.

Ref:
 - http://www.nbu.gov.sk/skcsirt-sa-20170909-pypi/
 - https://www.pytosquatting.org/

**Comment by jayfk** [comment]
Will do!

**Comment by Lucas-C** [comment]
FYI, the full experiment context: https://pytosquatting.org

**Comment by jayfk** [comment]
Thanks, added them a couple days ago: https://github.com/pyupio/safety-db/commit/b8a9d943c7ccc6624be87d0cc9b9e5970fbd83a9
