### ISSUE TITLE
pip 10 api breakage

### ISSUE THREAD

**Issue by jayfk** [pyupio/safety#90]
Quoting distutils-sig:

> We're in the process of starting to plan for a release of pip (the
long-awaited pip 10). We're likely still a month or two away from a
release, but now is the time for people to start ensuring that
everything works for them. One key change in the new version will be
that all of the internal APIs of pip will no longer be available, so
any code that currently calls functions in the "pip" namespace will
break. Calling pip's internal APIs has never been supported, and
always carried a risk of such breakage, so projects doing so should,
in theory, be prepared for such things. However, reality is not always
that simple, and we are aware that people will need time to deal with
the implications.

> Just in case it's not clear, simply finding where the internal APIs
have moved to and calling them under the new names is *not* what
people should do. We can't stop people calling the internal APIs,
obviously, but the idea of this change is to give people the incentive
to find a supported approach, not just to annoy people who are doing
things we don't want them to ;-)

> So please - if you're calling pip's internals in your code, take the
opportunity *now* to check out the in-development version of pip, and
ensure your project will still work when pip 10 is released.

> And many thanks to anyone else who helps by testing out the new
version, as well :-)

> Thanks,
Paul
_________

Safety uses `pip.get_installed_distributions` which has moved to https://github.com/pypa/pip/blob/master/src/pip/_internal/utils/misc.py#L333

**Comment by jayvdb** [comment]
Christmas has come early ; pip 9.0.2 broke it.

**Comment by omarish** [comment]
We just ran into this as well, using pip 10.0.0b2.

**Comment by jayvdb** [comment]
Maybe get ahead of the game and add a requirement `pip<10` until such time as the safety code has been updated to use `pip` via the command line interface.
c.f. https://github.com/pyupio/safety/issues/114#issuecomment-379233640

**Comment by jayvdb** [comment]
@di is looking at a new approach to solving this problem.
c.f. https://github.com/di/pytest-reqs/issues/13#issuecomment-381607494

**Comment by dgilge** [comment]
I also ran into this.

I don't know if this is an option:

> You can use `pkg_resources.working_set` for getting the same information. It's part of setuptools, which is probably already installed on your system.

See https://github.com/pypa/pip/issues/5243#issuecomment-381513000. As a result we might have another dependency: `setuptools`.

**Comment by ewhauser** [comment]
This has been fixed in newer versions of safety and should be closed.

**Comment by Jwomers** [comment]
Thanks all!
