### ISSUE TITLE
TypeError: object of type 'itertools.chain' has no len()

### ISSUE THREAD

**Issue by int-ua** [pyupio/safety#91]
* safety version: 1.6.0
* Python version: 3.4.3
* Operating System: Ubuntu

### Description

Trying to check a requirements.txt file raises an exception, see below.

### What I Did

```
$ safety check -r project/requirements.txt
...
File "venv/lib/python3.4/site-packages/safety/cli.py", line 64, in check
    checked_packages=len(packages),
```

**Comment by jayfk** [comment]
Thanks 👍
